# Tutorial — Running & Publishing Generated YTP Videos

This tutorial covers how to preview, process, optimize, subtitle, thumbnail, and publish the chaotic YTP videos generated by WebPoop.js. It includes practical ffmpeg commands and Windows (including Windows 8.1) guidance.

Contents
- Quick preview
- Re-encoding & optimization
- Audio safety & ear-rape handling
- Subtitles & meme text overlays
- Thumbnails & metadata
- Uploading to YouTube (recommended settings)
- Sharing & hosting
- Troubleshooting common issues
- Quick reference commands
- Legal & safety notes

---

## Quick preview

1. Use a reliable media player:
   - VLC (recommended cross-platform): https://www.videolan.org/vlc/
   - mpv or ffplay (`ffplay output.mp4`) for quick checks.

2. On Windows, double-click `output.mp4` or right-click → Open with → VLC. If codec issues appear, see "Re-encoding" below.

3. For a browser preview, serve the file via a local HTTP server and open in Chrome/Firefox:
   - Quick server:
     - Python 3: `python -m http.server 8000`
     - Node: `npx http-server .`
   - Then open `http://localhost:8000/path/to/output.mp4`.

---

## Re-encoding & optimization

Why re-encode?
- Ensure broad compatibility (H.264 + AAC).
- Reduce file size or increase quality.
- Fix container/codec issues from ffmpeg.wasm.

Recommended re-encode to MP4 (H.264 + AAC):
```
ffmpeg -i input.mp4 -c:v libx264 -preset fast -crf 18 -c:a aac -b:a 192k -movflags +faststart output_reencoded.mp4
```
- Lower CRF → higher quality (18 is visually near lossless); higher CRF (23–28) reduces size.
- `-movflags +faststart` optimizes MP4 for web streaming.

Faster / more compatible (older devices):
```
ffmpeg -i input.mp4 -c:v libx264 -preset veryfast -crf 23 -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -b:a 128k output_compatible.mp4
```

Batch re-encode multiple files (bash/powershell loop) — helpful when generating many YTPs.

---

## Audio safety & ear-rape handling

YTPs often include extreme volume jumps. Before publishing, normalize and optionally limit peaks.

Normalize loudness (recommended):
```
ffmpeg -i input.mp4 -af "loudnorm=I=-16:TP=-1.5:LRA=11" -c:v copy output_norm.mp4
```
- `I` = integrated loudness target, `TP` = true peak limit, `LRA` = loudness range.

Apply a limiter (cap peaks) — test first:
```
ffmpeg -i input.mp4 -af "loudnorm=I=-16:TP=-1.5:LRA=11,dynaudnorm" -c:v copy output_limited.mp4
```
If you want to experiment with "ear-rape" previews locally (WARNING: very loud), you can increase volume for testing, but never upload without warning:
```
ffmpeg -i input.mp4 -af "volume=12dB" -c:v copy output_loud.mp4
```
Always cap peaks for published versions — use loudnorm/dynaudnorm and test with headphones (start quiet).

---

## Subtitles & meme text overlays

1. Soft subtitles (SRT file, selectable in players/YouTube):
```
ffmpeg -i input.mp4 -i subs.srt -c copy -c:s mov_text output_with_subs.mp4
```
- `mov_text` is used for mp4 soft subtitles (works on many platforms including YouTube upload).

2. Burn-in subtitles or memes (drawtext) — text permanently on video (Impact meme text):
- Provide the full path to an Impact font file. Windows usually has `C:\Windows\Fonts\impact.ttf`.
```
ffmpeg -i input.mp4 -vf "drawtext=fontfile='C\\:/Windows/Fonts/impact.ttf':\
text='MEME TEXT':fontcolor=white:fontsize=72:box=1:boxcolor=black@0.6:boxborderw=10:\
x=(w-text_w)/2:y=h-(text_h*1.5)" -c:a copy output_meme.mp4
```
- For dynamic text per timestamp, generate multiple drawtext filters or use an ASS subtitle file (with styling) and burn it in:
```
ffmpeg -i input.mp4 -vf "subtitles=memes.ass" -c:a copy output_burned.mp4
```

---

## Thumbnails & metadata

Create a thumbnail frame (example at 5 seconds):
```
ffmpeg -ss 00:00:05 -i input.mp4 -frames:v 1 -q:v 2 thumbnail.jpg
```
- Use `-ss` before `-i` for fast seek or after `-i` for frame-accurate.

Generate multiple preview thumbnails (every N seconds):
```
ffmpeg -i input.mp4 -vf "select='not(mod(t,5))',scale=1280:-1" -vsync vfr -q:v 2 thumbs_%03d.jpg
```

Add metadata (title, artist) to MP4:
```
ffmpeg -i input.mp4 -metadata title="WebPoop YTP" -metadata artist="Creator" -codec copy output_meta.mp4
```

---

## Uploading to YouTube — recommended settings

Preferred format:
- Container: MP4
- Video codec: H.264 (High Profile)
- Audio codec: AAC-LC, 48 kHz, stereo
- Color: Rec.709
- Resolution & bitrates (variable):
  - 720p: 5 Mbps (approx) / CRF ~18–23
  - 1080p: 8–12 Mbps
  - 1440p / 4K: much higher — use higher bitrate or target CRF and two-pass if needed
- Frame rate: Keep original (24 / 25 / 30 / 60). Avoid re-timing unless necessary.
- Keyframe interval: 2 seconds recommended by YouTube (if controlling).

YouTube upload tip:
- Use a final file with `-movflags +faststart` for streaming.
- Include an appropriate title, description, timestamps (chapters), and content warnings (ear-rape, explicit language).
- Add captions: upload SRT to YouTube or include embedded captions as soft subtitles.

---

## Sharing & hosting

- Large file sharing: use Google Drive, Dropbox, or WeTransfer for sending raw outputs.
- For embeddings on the web, transcode smaller versions (lower resolution/CRF).
- For short clips (TikTok/Reels/Instagram), reformat to vertical (9:16) with cropping/scale and tight duration limits.

Convert for social vertical upload (example center-crop to 9:16):
```
ffmpeg -i input.mp4 -vf "scale=1080:-1, crop=1080:1920" -c:v libx264 -crf 23 -c:a aac -b:a 128k output_vertical.mp4
```

---

## Troubleshooting common issues

- "No video playback" or black video:
  - Re-encode with H.264: use the re-encode command above.
  - Check that mp4 container has video track: `ffprobe -v error -show_entries stream=index,codec_type,codec_name input.mp4`

- Audio out-of-sync:
  - Try re-encoding with `-async 1 -vsync 1` or explicit audio re-sampling:
    ```
    ffmpeg -i input.mp4 -c:v libx264 -c:a aac -af "aresample=async=1" output_sync.mp4
    ```
  - Use `-itsoffset` to shift audio if you know the offset:
    ```
    ffmpeg -itsoffset 0.2 -i audio.mp3 -i video.mp4 -map 1:v -map 0:a -c copy output_synced.mp4
    ```

- Subtitles not visible in MP4:
  - Ensure you used `-c:s mov_text` for MP4 soft subtitles.
  - Some players may not show subs for MP4; test in VLC and upload to YouTube to verify.

- Crashes or memory errors with ffmpeg.wasm:
  - Re-encode or process on native ffmpeg (install ffmpeg.exe and use fluent-ffmpeg or CLI).
  - Reduce resolution/length or increase Node memory: `node --max-old-space-size=4096 script.js`

---

## Windows 8.1 notes

- Use native `ffmpeg.exe` (download static build) for best compatibility/performance:
  - Add `C:\path\to\ffmpeg\bin` to PATH, or call `C:\path\to\ffmpeg\bin\ffmpeg.exe` explicitly.
- PowerShell example:
  ```
  & 'C:\ffmpeg\bin\ffmpeg.exe' -i input.mp4 -c:v libx264 -crf 23 output.mp4
  ```
- If `@ffmpeg/ffmpeg` (wasm) is used in Node on Windows 8.1, ensure `node-fetch@2` polyfill or Node >= 18 fetch support.

---

## Quick reference commands

Re-encode to web-ready MP4:
```
ffmpeg -i in.mp4 -c:v libx264 -preset fast -crf 18 -c:a aac -b:a 192k -movflags +faststart out.mp4
```

Normalize audio:
```
ffmpeg -i in.mp4 -af "loudnorm=I=-16:TP=-1.5:LRA=11" -c:v copy out_norm.mp4
```

Create thumbnail at 5s:
```
ffmpeg -ss 00:00:05 -i in.mp4 -frames:v 1 -q:v 2 thumb.jpg
```

Embed SRT into MP4 (soft subs):
```
ffmpeg -i in.mp4 -i subs.srt -c copy -c:s mov_text out_subs.mp4
```

Burn Impact meme text:
```
ffmpeg -i in.mp4 -vf "drawtext=fontfile='C\\:/Windows/Fonts/impact.ttf':text='MEME':fontsize=72:fontcolor=white:stroke_color=black:stroke_w=3:x=(w-text_w)/2:y=h-(text_h*1.5)" -c:a copy out_meme.mp4
```

Split into 10s segments:
```
ffmpeg -i in.mp4 -c copy -map 0 -f segment -segment_time 10 -reset_timestamps 1 out%03d.mp4
```

---

## Legal & safety notes

- Copyright: YTPs commonly reuse copyrighted clips — ensure compliance with copyright law and platform policies. Fair use is context-dependent; if uncertain, avoid publishing copyrighted materials without permission.
- Content warnings: include clear warnings for extreme audio (ear-rape), flashing content (photosensitive seizure risk), or explicit language.
- Respect privacy and avoid creating deepfakes or manipulative content that harms individuals.

---

If you want, I can:
- produce ready-to-run Windows PowerShell scripts wrapping the above ffmpeg commands,
- add an automated "post-process" module to WebPoop.js that runs normalization, thumbnail generation, and optional subtitle embedding,
- generate YouTube upload presets or a sample Google API upload script.

Which of those would you like next?